name: Run BDD Tests

on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: string
        description: Environment to run tests against (e.g., staging, production)
      target:
        required: true
        type: string
        description: Target to run tests against (e.g., staging, production)

permissions:
  contents: read

jobs:
  bdd-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - name: Run BDD tests
        run: npm run test:bdd -- --env=${{ inputs.environment }} --target=${{ inputs.target }}